### ISSUE TITLE
Bug report: width of cityname in CCRP logo

### ISSUE THREAD

**Issue by traveller195** [colouring-cities/colouring-core#1099]
**Describe the problem**
I took the colouring-core version of 16th feb 2023 and use this version now to adapt Colouring Dresden.
so, the initial quick step was to set some configs (see https://github.com/colouring-cities/colouring-core/blob/master/docs/configuring-colouring-cities.md )

Unfortunately, the width of the words "COLOURING" and "DRESDEN" is not equal in the created logo.

![grafik](https://user-images.githubusercontent.com/57902113/219746478-cb895b4f-353b-4e32-b742-c286eb72ac9b.png)

**To Reproduce**
1. see https://github.com/colouring-cities/colouring-core/blob/master/docs/configuring-colouring-cities.md
2. set cityname parameter and deploy a build
3. open Colouring Cities platform and have a look to the logo in the upper left corner

**Expected behavior**
both words should have equal width

**Screenshots**
see above

**More information**
maybe you @mdsimpson42  know a proper CSS rule which could be adapted. So, that it is also included to colouring-core if other Colouring Cities project will be customized by configuring

**Comment by traveller195** [comment]
additional note for documentation:

issues could be handled there
https://github.com/colouring-cities/colouring-core/blob/master/app/src/frontend/components/logo.tsx
or better within CSS file
https://github.com/colouring-cities/colouring-core/blob/master/app/src/frontend/components/logo.css

logo is not a png graphic (how it was solved in the past, I suppose), but now a component offering parameters for the text. So, it is easiert adaptable.

**Comment by mdsimpson42** [comment]
There doesn't seem to be an easy way to do this. It doesn't look like it can be done with 'pure' CSS and I've looked into a couple of different React-based solutions, but I either can't install the modules or can't get them to work. Most of them resize the text to fit the available space rather than adjusting the spacing of the letters, which isn't what we want.

I'm not sure there's a solution that would work as well for "Colouring Hull" as it would for "Colouring Loughborough" , for example.

![image](https://user-images.githubusercontent.com/21125422/231886228-aed07150-6f7c-4a32-b5b6-e83b1f6235b8.png)
![image](https://user-images.githubusercontent.com/21125422/231886352-a1ecd542-8a73-4677-98ab-832dc6697c93.png)

I can adjust the spacing between the letters in the code based on the length of the city name, but it will be fiddly to get it to work for any city name we might have to use. (I hope we never have to make "Colouring Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch"!!)
