### ISSUE TITLE
Remove/Reduce Duplicate Code?

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1155]
There are a lot of categories (e.g. Age and History) where there are massive if statements and then a lot of duplicate code that appears in both outputs.  

It is problematic because sometimes I make changes and they don't appear (because they're in the 'wrong' part of the if statement), or it is easy to make changes only in one place and not the other (so some fields are missing on some buildings).  

- Why is this the case?
    - (In age and history, it seems to be conditional on the building date source?)
- Can we restructure the code in some way to reduce code repetition (and make it easier to edit properties)?

**Comment by polly64** [comment]
Send me a link and we can chat now


Polly Hudson
Senior Research Fellow, The Alan Turing Institute
Project Lead:  Colouring Cities Research Programme
https://www.turing.ac.uk/research/research-projects/colouring-london-and-colouring-cities-research-programme

The Alan Turing Institute is the UK's national institute for data science and artificial Intelligence.
The Alan Turing Institute is a limited liability company, registered in England with registered number 09512457 with registered offices at British Library, 96 Euston Road, London, England, NW1 2DB. We are also a charity registered in England with charity number 1162533. DISCLAIMER: Although we have taken reasonable precautions to ensure the completeness and accuracy of this e-mail, transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or be incomplete. If you receive a suspicious or unexpected email from us, or purporting to have been sent on our behalf, particularly containing different bank details, please do not reply to the email, click on any links, open any attachments, or comply with any instructions contained within it. Our Transparency Notice found here - https://www.turing.ac.uk/transparency-notice sets out how and why we collect, store, use and share your personal data and it explains your rights and how to raise concerns with us.

On 18/05/2023, 11:43, "Mike Simpson" ***@***.***> wrote:


There are a lot of categories (e.g. Age and History) where there are massive if statements and then a lot of duplicate code that appears in both outputs.

It is problematic because sometimes I make changes and they don't appear (because they're in the 'wrong' part of the if statement), or it is easy to make changes only in one place and not the other (so some fields are missing on some buildings).

  *   Why is this the case?
     *   (In age and history, it seems to be conditional on the building date source?)
  *   Can we restructure the code in some way to reduce code repetition (and make it easier to edit properties)?

**Comment by polly64** [comment]
@tomalrussell @matkoniecz any thoughts on this?

**Comment by matkoniecz** [comment]
Do you mean https://github.com/colouring-cities/colouring-core/blob/master/app/src/frontend/building/data-containers/age.tsx code or some other?

**Comment by matkoniecz** [comment]
In general, if refactoring is possible without making everything more complicated then it would definitely make sense.

**Comment by polly64** [comment]
@mdsimpson42 you could also ask Ed if he knows reason, he's always v helpful on queries

**Comment by mdsimpson42** [comment]
As mentioned in the above commit, I did a side-by-side comparison of the code in each part of the if statement. There were no functional differences, but there were a couple of bugs where one version was out of date or wrong. I have removed the if statement and tidied up the remaining code. I will close this issue once the changes are merged (and once I've checked that there aren't other files with similar duplicate code in them).
