### ISSUE TITLE
Look into options for a Showcase site

### ISSUE THREAD

**Issue by mdsimpson42** [colouring-cities/colouring-core#1233]
We want to revisit the idea of a Showcase for Colouring Cities (as discussed in #644). Adding a new issue to keep it on our radar.

The current suggestion is that we use an existing template to create a separate website, which we can get hosting for, and then have as a subdomain of Colouring Cities, like with [Colouring Athens](https://athens.colouringcities.org/). i.e. http://showcase.colouringcities.org.

Users would need to be able to log in and create showcases, providing a title, image, description and link. An admin (Polly) would then need to approve the showcase before it gets shown publically on the site.

**Comment by mdsimpson42** [comment]
I've asked if any of my colleagues know of a suitable template that can be used to create this site in as short a time as possible.

**Comment by polly64** [comment]
Hi @mdsimpson42 here is a draft template  - we also need to be able to easily add more over time.

- **Case Study name**
e.g The Use of Historical Data in Rule-Based Modelling for Scenarios to Improve Resilience within the Building Stock

- **300 word max description**
e.g Digital documentation has become integral to the preservation, analysis and communication of historical sites. New platforms are now being developed that involve complex 3D models and allow the analysis of spatial data. These include procedural modelling, a technique that enables the rapid development of ‘dynamic’ 3D environments, and generation of simulations for entire cities, resulting in low cost, high resolution 3D city models. Though procedural modelling has been used in the context of archaeology to ‘recreate’ cities at specific historic time points, the use of historical data in the development of rule-based procedural models for current cities has been little explored. Here, we test the extent to which construction age data, historical building regulations and architectural knowledge can be used in the generation of procedural rules, and the level of detail and potential impact that these models may have. Rather than creating an accurate representation of the city, we instead seek to simulate the way in which urban areas are likely to behave under certain conditions, in order to test what-if? planning scenarios. This allows us to explore more flexible ways of digitally ‘creating’ cities, past and present, and to gain insights into underlying ‘rules’ that govern their physical form

- **Keywords**
e.g Procedural modelling, building age data, CityEngine, Camden, Victorian House, Historical data

- **Date of publication/completion**
e.g 15th Nov 2018

- **Authors/Creators**
e.g. Dr Flora Roumpani, Polly Hudson and Professor Andrew Hudson-Smith
 
- **Organisation**
e.g. Centre for Advanced  Spatial Analysis, University College London

- **Sector type**: Industry; Academia; Government; 3rd Sector/Non-profit; Citizens/Community; Other

- **Organisation location** (city, Country)
-e.g London, UK

- **Case study format**: Film/Video, academic paper, article, other
e.g Academic paper and youtube video

- **Case study link/s**
e.g https://www.tandfonline.com/doi/abs/10.1080/17567505.2018.1517142
add youtube link

- **Are the data used in this case study open?** (Yes/No/Partially)
e.g Partially

**If yes or partially open box asking for data source link**
e.g https://colouringlondon.org/view/age/2503349

-----

- **Which Country does your case study relate to: (add standard list of countries)**
e.g UK

- **What locality, city or region does it relate to**
e.g Camden, London

- **Which Colouring Cities data categories is your case study most relevant to in terms of the main type of data used?** 
Location/Building ID, Land use, Typology, Size, Construction & Materials, Age and History, Street Context (including streets, pavements, green context etc), Planning Controls,  Energy Performance, Resilience/Disaster Management, Community (please see https://colouringlondon.org/ for subcategories)
e.g Age and History, Street context 

- **Does it relate mainly to domestic, non-domestic, or mixed use buildings, or all of these?**
Domestic, Non-domestic, Mixed Use, All types
e.g Domestic
- If non-domestic chosen open up: Which building land use/s does the case study most closely relate to?
- Recreation and Leisure; Utilities; Transport; Public/Community services; Retail; Industry and Business; Agriculture, Fisheries or Minerals.
e.g n/a

- **Which areas of research and practice is your case study most relevant to? (please tick more than one if relevant)**
_Housing,_ _Planning_, Energy & New Zero, Sustainable Urban Environments, Natural Environment, Food and Agriculture, Culture, Media and Sport, Transport, Business, Industry, Demographics, Climate Resilience, Disaster Management, Health and well-being, Education, Security/Defence, Justice/Spatial justice, Crime, Sustainable Infrastructure, Data standards, Communications, Digital Twins & Simulation models, AI and Machine learning in data capture, AI and Machine learning in data analysis, Historical data, procedural modelling or Other-please specify
e.g   underlined above

 Please add any other tags



Concept design image 2017
![image](https://user-images.githubusercontent.com/42236514/102720025-8e786480-42e9-11eb-9cf6-cec9082d91fa.png)

**Comment by mdsimpson42** [comment]
So, there's a couple of things we could use, I'll keep posting as I discover them.

First, I was updating our team website and I thought "this is pretty close to the functionality we need". You have a series of tiles for each team member and when you click on them it takes you to a page with more details.

https://rse.ncldata.dev/team

The only problem with that is that the pages are created using markdown files and have to be built into web pages, which is not as quick and easy-to-use as it would be if the user could log in and create their own showcase/case study.

**Comment by mdsimpson42** [comment]
Another option might be a blogging template, which we could adapt for our purposes...

https://writeologytemplate.webflow.io/

That way, users could create blog posts based on their showcase, but that possibly gives them too much creative freedom and doesn't let us specify what data we collect about each project.

**Comment by mdsimpson42** [comment]
One question: would we be willing to pay for a template, if it lets us throw something together in a few days? I've seen a few for around £80 to £130...

**Comment by polly64** [comment]
Thanks Mike. Would need to be free and be looking like it was staying free.

**Comment by mdsimpson42** [comment]
Okay. It would just be a one-off payment to download the template; then we could build the website from that, but I appreciate that budgets are tight.

Basically, its the difference between: 

- me spending a couple of days building something from scratch, preferably using a framework I'm familiar with (Angular) 
- or finding a template that's similar to what we want and then customising it, which - in theory - wouldn't take as long (but I haven't yet found a suitable template). 

At this point, I'm leaning towards just building it myself, then we can get it exactly how we want it. I've built a couple of apps using this framework before, so it shouldn't take long to get something up and running.

**Comment by polly64** [comment]
great @mdsimpson42 that sounds good, send me meeting link for today

**Comment by mdsimpson42** [comment]
A prototype version of the Showcase website is now being developed.
- The site is deployed here (and will automatically update when new code is pushed): [https://colouringcities.org/showcase](https://colouringcities.org/showcase)
- Code is here: [https://github.com/colouring-cities/showcase](https://github.com/colouring-cities/showcase)

The current plan is to implement the interface in Angular and the backend in Strapi. I've begun implementing functionality with dummy data for now, to get an idea of what the site will look like/how it will work. I plan to add to this over the next few weeks and then look into activating the Strapi backend as soon as possible.

**Comment by polly64** [comment]
@mdsimpson42 @stuartlynn lets organise a meet up re getting this section activated
can we look at this format as for cheffins  below and other sites like it where you have dropdowns for options at top and then can choose, scroll down and click on  a) entry summaries  or b) just gallery images
https://www.cheffins.co.uk/fine-art/catalogue-view,the-fine-sale_267.htm. I think this is more elegant than side bar I originally planned (as image above) 

- [ ] The Colouring Cities Research Programme Logo would be at the top large
- [ ] Then a Title  'Impact studies - Uses for Colouring Cities data, and other microspatial building data sources' 
- [ ] Then Options for 'Search Impact studies' or 'Add a study' 
-
- [ ] If search is chosen: select from 
i) Data source: Select Colouring Cities or Other. Then provide same CCRP dropdown categories and subcats nested within these, for both
ii) Sector : (All, academia, government, 3rd sector, industry, community)
iii) Subject area:  (see above) could be predictive text - please advise best way 
iv) Country/Author: Option to add author name or country, and then search for each
v) Year published: All or option to add

- [ ] Then option to show as gallery or as list with image and more detail
- [ ] Need to be able to add from anywhere in world- and to go through academic moderation within that country - ideally would be queued and then alert to host organisation to check and release.
