### ISSUE TITLE
add building age button to access map

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1242]
@mdsimpson42 

- [x] can you add building age map button under 'Age'
- [x] we need to look at button wording for all categeories as confusing when refers back to default
- [x] #1243

**Comment by mdsimpson42** [comment]
What if...

1. We change the colour of the buttons when they're used to change the key. (The ones under Survival Tracking in Age and History change the layers that are visible, and so it makes sense for them to be styled in the same way as the "Layer Options" buttons.) Then we are differentiating the other buttons from those ones, as their behaviour is slightly different.

2. We make the buttons disappear when you click them. So you click on it to change the key, and then it disappears, only reappearing when you change the key. Then we don't have to worry about the wording on the "off" version of the button or the logic of what other key options to show when you click it.

3. We make the wording more consistent across all categories ("Click here to show [feature]")

I might make these changes for one of the categories and deploy to staging so we can test it and see how it works?

**Comment by polly64** [comment]
@mdsimpson42 yes can you test? can we also test clicking on a new subtitle and this changing the key- and vice versa changing the key and it opening the correct section- this is my preferred?

**Comment by mdsimpson42** [comment]
- A button has been added under Age (but it isn't visible unless a different category is selected.
- The wording on all buttons has been updated to be more consistent across all categories. Buttons now disappear when clicked, so we don't have to worry about 'default' or their behaviour when you unclick them.

The alternative might be to grey out and disable the button when its clicked, rather than making it invisible...
