### ISSUE TITLE
Agreement on  introductory text

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-core#1291]
We are revising the CCRP common introductory text here. Please could you either add cany comments below or add ok if you are happy with it, thanks

'Colouring  (add relevant city/ country) is an open knowledge initiative that provides open spatial data on (add relevant city's/ country's ) buildings for everyone to use.  If you are a resident, or work in academia, government, industry or the third sector, any information you can add to our platform is greatly appreciated.

Colouring (X) forms part of the Colouring Cities Research Programme (CCRP), run by The Alan Turing Institute https://www.turing.ac.uk/research/research-projects/colouring-cities-research-programme (changeable) and involving an international consortium of academic institutions, building networked CCRP platforms and pooling research expertise. Our collective aim is to provide access to standardised data able to help accelerate improvements to the quality, efficiency, resilience and sustainability of buildings and urban areas, and to help meet net zero goals 

All [data collected](e.g https://colouringlondon.org/data-extracts.html) and [code](https://github.com/colouring-cities/colouring-core) are free to download, use and share under open licence terms. Our [open manual](https://github.com/colouring-cities/manual/wiki) also provides non-technical information for anyone interested in our research.

**Comment by polly64** [comment]
@matkoniecz could you replace the Colouring Britain text with this asap many thanks

**Comment by matkoniecz** [comment]
What about "What you are contributing to" section in contributor agreement at https://colouringlondon.org/contributor-agreement.html ?

Should "is a free knowledge exchange platform"  be also changed to "is an open knowledge initiative" ?

See also #1343

**Comment by matkoniecz** [comment]
there is idea to make this configurable who rans given instance but it seems to me that "run by" could be easily misinterpreted as referring to the entire program

Imagine

> Colouring Kraków forms part of the Colouring Cities Research Programme (CCRP), run by AGH University of Krakow https://www.agh.edu.pl/en/university/page

-----------------

maybe rather than

> Colouring (X) forms part of the Colouring Cities Research Programme (CCRP), run by The Alan Turing Institute https://www.turing.ac.uk/research/research-projects/colouring-cities-research-programme (changeable)

it may be

> Colouring (X) run by The Alan Turing Institute https://www.turing.ac.uk/research/research-projects/colouring-cities-research-programme (changeable) forms part of the Colouring Cities Research Programme (CCRP)

? Or some other phrasing.

**Comment by matkoniecz** [comment]
Note that currently we have

>             {config.projectBlurb}
>            &nbsp;The Colouring Cities Research Programme (CCRP), led by the Alan Turing Institute,
>            is <a href="https://github.com/colouring-cities/colouring-cities.github.io">an international consortium of academic institutions</a> involved
>            in building research. Our aim is to maximise accessibility to building-level data across countries, 
>            to help improve stock quality, efficiency, sustainability and resilience and meet net-zero goals.


in practice it can be for example

> Colouring Britain is part of Colouring Cities. The Colouring Cities Research Programme (CCRP), led by the Alan Turing Institute, is [an international consortium of academic institutions](https://github.com/colouring-cities/colouring-cities.github.io) involved in building research. Our aim is to maximise accessibility to building-level data across countries, to help improve stock quality, efficiency, sustainability and resilience and meet net-zero goals.

**Comment by mdsimpson42** [comment]
I've tweaked this slightly. 

The second paragraph starts:
"Colouring {City Name} forms part of the Colouring Cities Research Programme (CCRP), managed by [The Alan Turing Institute](https://www.turing.ac.uk/research/research-projects/colouring-cities-research-programme)," 

(do we want that link to be configurable?)

The last paragraph looks like this:
"All data collected (e.g [data-extracts](http://localhost:8080/data-extracts.html)) and [code](https://github.com/colouring-cities/colouring-core) are free to download, use and share under open licence terms. Our [open manual](https://github.com/colouring-cities/manual/wiki) also provides non-technical information for anyone interested in our research." 

Otherwise, it doesn't fit on the sidebar:
![image](https://github.com/colouring-cities/colouring-core/assets/21125422/50fedd10-4721-4353-bb5a-2673b28a857f)

I also changed the data extracts link so that it links to the data for that version of the platform instead of linking to Colouring London (especially as we're starting to retire colouringlondon.org in favour of colouringbritain.org)

---

Let me know if you want me to tweak it before I deploy to staging.

**Comment by mdsimpson42** [comment]
We discussed this in the international engineering meeting. Other PIs are going to look at the new wording and see if they are happy or want to make any changes.
