### ISSUE TITLE
Allow admin users to edit map colour scales

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-core#744]

**Comment by matkoniecz** [comment]
So basically as the first step we weould need to move that into database rather than hardcoding in https://github.com/colouring-cities/colouring-london/blob/master/app/map_styles/polygon.xml and https://github.com/colouring-cities/colouring-london/blob/master/app/src/frontend/config/category-maps-config.ts

`app/map_styles/polygon.xml` would need to be dynamically generated, without restarting the server

editing colours should also drop caches
